MK_CFG_DIR = /home/y/share/make_cfg
include $(MK_CFG_DIR)/make.defs

LIBNAME = nshm
LIBVERSION=1
CSRC = nshm.c

WARN +=
OPPFLAGS += 
DEPOBJS = 
LDFLAGS = 
LDLIBS = -lpthread

include $(MK_CFG_DIR)/make.rules
